### ISSUE TITLE
Mesh skeleton not proper for straight cylinder

### ISSUE THREAD

**Issue by Vysakh5391** [navis-org/skeletor#18]
Hi @tomka and @schlegelp ,

I have an STL file of straight cylinders which I would like to skeletonize. Since they are tubular, I used the wavefront method to achieve the skeleton. You can download the STL file from this link.

https://drive.google.com/file/d/1qfxWzML-2eowcJXYhpm4bcHOMIUumTax/view?usp=sharing

The code I used is:
```
import trimesh
import skeletor as sk
mesh = trimesh.load_mesh('straight_cylinders.stl')
mesh.show()
skel = sk.skeletonize.by_wavefront(mesh, step_size=1)
# sk.post.radii(skel, mesh, method='ray', aggregate='min', n_rays=2000, projection='tangents', fallback='knn')
skel.show()
```

The skeleton I am getting is not proper for 4 out of the 5 cylinders. Since I am new to this approach, I am not sure what I am missing. Looking forward to your help.

The skeleton looks like this.
![image](https://user-images.githubusercontent.com/47824150/137631351-642d64c0-ad38-4772-9ca1-21975b767746.png)

**Comment by schlegelp** [comment]
The problem with using the wavefront method on these cylinders is that they are unevenly sampled: you have lots of vertices at each end (defining the "lids") but none along the length the cylinder. Because the wave "moves" from vertex to vertex that low vertex resolution results in bad skeletons.

<img width="573" alt="Screenshot 2021-10-17 at 15 42 29" src="https://user-images.githubusercontent.com/7161148/137632460-08d16ea9-b440-489a-8d98-da707d516c29.png">

There are a few things you can try (in combination or alone):
- subdivide the cylinders to have all edges roughly the same size 
- cast multiple waves to compensate for where the wave is initialised (`sk.skeletonize.by_wavefront(mesh waves=100`)
- try other methods: e.g. mesh contraction (`sk.pre.meshcontraction`) followed by `sk.skeletonize.by_vertex_clusters` or `sk.skeletonize.by_teasar`
