### ISSUE TITLE
Issue when computing skeleton (with non-watertight mesh)

### ISSUE THREAD

**Issue by yvanblanchard** [navis-org/skeletor#39]
Hello,

I have a non-watertight mesh (OBJ) and the output skeleton is KO (very few points).

Mesh:
![image](https://github.com/navis-org/skeletor/assets/63931618/debf8ac3-6423-496e-b520-f949e123c700)
![image](https://github.com/navis-org/skeletor/assets/63931618/f4d0fe86-a593-4d06-b4ff-080f4c2ffed3)

Here is my input file:
[MeshToSkeletonize.zip](https://github.com/navis-org/skeletor/files/11584127/MeshToSkeletonize.zip)

Here is the output skeelton file (swc):
![image](https://github.com/navis-org/skeletor/assets/63931618/07baa729-99f2-409a-978a-befb306e5732)

**Comment by yvanblanchard** [comment]
Moreover, I tried to display the skeleton result, but it failed. It said that trimesh.viewer.windowed requires pyglet<2 (I had version 2.0.7).
Then, Installed pyglet-1.2.4 , but I got another error: (missing clock attribute):
![image](https://github.com/navis-org/skeletor/assets/63931618/1fa94d78-f8d1-4582-90c3-3ea65610d852)

**Comment by schlegelp** [comment]
Hi! Two separate issues here.

1. The skeleton:

I quickly loaded your mesh into Blender to look at the structure. Not sure if you're familiar with that software but in the screenshot you can see the vertices and the edges/faces between them. The highlighted on is a face that I selected and then moved a little to the side. As you can see it's disconnected by which I mean your mesh consists of faces that each have their entirely independent set of vertices. This is an issue since `skeletor` uses the mesh's connectivity to generate skeletons.

<img width="1672" alt="Screenshot 2023-05-28 at 13 22 38" src="https://github.com/navis-org/skeletor/assets/7161148/c0969d6f-10b7-4026-bc2e-76b19a95d7fd">

Fortunately, we can fix this issue using `trimesh`:

```python
>>> import trimesh as tm 
>>># Load mesh and forbid trimesh run fixes
>>> m = tm.load('MeshToSkeletonize.obj', process=False)
>>> # Inspect - note the number of vertices
>>> m
<trimesh.Trimesh(vertices.shape=(1635, 3), faces.shape=(545, 3))>

>>> # Check the number of connected components
>>> # (i.e. how many disconnected pieces your mesh consists of)
>>> import networkx as nx 
>>> len(list(nx.connected_components(m.vertex_adjacency_graph)))
545 
>>> # As expected: 545 = the number of faces in your mesh

>>> # Now let's see if we can tell trimesh to merge vertices and generate one continuous mesh 
>>> m.merge_vertices(merge_tex=True, merge_norm=True)
>>> # Note the reduction in vertices:
>>> m
<trimesh.Trimesh(vertices.shape=(473, 3), faces.shape=(545, 3))>

>>> # Check connected components again 
>>> len(list(nx.connected_components(m.vertex_adjacency_graph)))
2
>>> # Looking at your mesh this makes sense since there is a small corner that is 
>>> # entirely disconnected
```

OK, with the mesh fixed we can try to skeletonise your mesh. I had a really quick crack at it and this is the best I could come up with:

```python
>>> # Let's try skeletonizing the fixed mesh 
>>> import skeletor as sk 
>>> s = sk.skeletonize.by_teasar(m, inv_dist=10)
>>> s 
<Skeleton(vertices=(244, 3), edges=(242, 2), method=teasar)>
```

<img width="533" alt="Screenshot 2023-05-28 at 13 48 10" src="https://github.com/navis-org/skeletor/assets/7161148/1a6e33c0-e316-4a53-8d96-4abd3e8638f9">

As you can see it did _something_ but probably not what you were hoping for. Some notes:
- `skeletor` is designed to generate tree-like (acyclic) skeletons (i.e. each vertex has exactly one or no parent) which is why you get the breaks in your honeycomb structure. This is a limitation of the output format (SWC) but in theory I could rewrite the code to optionally not break-up cycles. Alternatively: you could use the skeleton --> mesh vertex map (`s.skel_map`) to heal the breaks by re-introducing edges according to the original mesh.
- Your mesh has a fairly low vertex count. That's perfect for visualisation but some of the skeletonization methods (e.g. mesh contraction or the wavefront method) don't work well on low-polygon, geometric meshes.

2. `skeletor` uses `trimesh`'s visualisation functions and from the backtrace in your screenshot it looks like the issue is with `trimesh` not `skeletor`. I would recommend you check the issue in the `trimesh` Github [repository](https://github.com/mikedh/trimesh) and open one there if you don't find an answer. 

Hope this is at least somewhat helpful!

**Comment by yvanblanchard** [comment]
Thank you for your detailed reply .

I followed your advice, and remesh my model for having a much finer mesh, and also check again for disconnected faces (merge_vertices).
![image](https://github.com/navis-org/skeletor/assets/63931618/3a73d637-a111-45d0-813b-ef0c0fd55d38)
File:
[MeshToSkeletonizeRemeshedFiner.zip](https://github.com/navis-org/skeletor/files/11584886/MeshToSkeletonizeRemeshedFiner.zip)

I also tried your skeleton method (by_teasar, with inv_dist of 10mm).
But it leads to this bad/unexpected result:
Notice that it does not matter is skeleton lines are not fully connected (zero or one parent max), but I need the skeleton to be perfeclty at medial position of 'branches' shapes of course.
![image](https://github.com/navis-org/skeletor/assets/63931618/4dd0c6be-c0b5-4c23-92df-b2cae975b8da)

**Comment by schlegelp** [comment]
The TEASAR method doesn't produce centred lines unfortunately.

With the higher res mesh you could try the wavefront method though:

```python
>>> m = tm.load('/Users/philipps/Downloads/MeshToSkeletonizeRemeshedFiner.obj')
>>> m.merge_vertices(merge_tex=True, merge_norm=True, digits_vertex=5)
>>> s = sk.skeletonize.by_wavefront(m, waves=1)
```

<img width="608" alt="Screenshot 2023-05-28 at 15 54 12" src="https://github.com/navis-org/skeletor/assets/7161148/dc2ff4a0-6eb6-4caa-b9b0-af34627008b8">

**Comment by yvanblanchard** [comment]
Thank you again.
Result is much better, but still lots of 'artefacts'.
I think I will use another method, maybe with some heuristic..
![image](https://github.com/navis-org/skeletor/assets/63931618/562c9743-5124-4eed-a195-924dad8e4714)

**Comment by schlegelp** [comment]
No problem. These are likely small false-positive side branches that you could prune away in post-processing (see screenshot). That said: you will not get a geometrically perfect centreline from any skeletonization method implemented in this library, I'm afraid.

<img width="722" alt="Screenshot 2023-05-28 at 16 07 48" src="https://github.com/navis-org/skeletor/assets/7161148/830c3620-addc-4062-a828-04d92f745005">
